[package]
name = "ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conv = "0.3"
derive_builder = "0.12"
ndarray = "0.15"
ndarray-rand = "0.14.0"
rand = "0.8"
